---
name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: Ruby cache
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/local/rubies
          key: ruby-2.6.5

      - name: Rubygems cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Install ruby
        uses: clupprich/ruby-build-action@master
        id: ruby
        with:
          ruby-version: 2.6.5
          cache-available: ${{ steps.cache.outputs.cache-hit == 'true' }}

      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run ruby tests
        run: |
          bundle exec rake

      - name: Run lint
        run: |
          bundle exec rubocop
